const allCountries = [
  { iso: "af", name: "Afganistán", flag: "🇦🇫" },
  { iso: "al", name: "Albania", flag: "🇦🇱" },
  { iso: "de", name: "Alemania", flag: "🇩🇪" },
  { iso: "ad", name: "Andorra", flag: "🇦🇩" },
  { iso: "ao", name: "Angola", flag: "🇦🇴" },
  { iso: "ai", name: "Anguila", flag: "🇦🇮" },
  { iso: "ag", name: "Antigua y Barbuda", flag: "🇦🇬" },
  { iso: "sa", name: "Arabia Saudita", flag: "🇸🇦" },
  { iso: "dz", name: "Argelia", flag: "🇩🇿" },
  { iso: "ar", name: "Argentina", flag: "🇦🇷" },
  { iso: "am", name: "Armenia", flag: "🇦🇲" },
  { iso: "aw", name: "Aruba", flag: "🇦🇼" },
  { iso: "au", name: "Australia", flag: "🇦🇺" },
  { iso: "at", name: "Austria", flag: "🇦🇹" },
  { iso: "az", name: "Azerbaiyán", flag: "🇦🇿" },
  { iso: "bs", name: "Bahamas", flag: "🇧🇸" },
  { iso: "bd", name: "Bangladés", flag: "🇧🇩" },
  { iso: "bb", name: "Barbados", flag: "🇧🇧" },
  { iso: "bh", name: "Baréin", flag: "🇧🇭" },
  { iso: "be", name: "Bélgica", flag: "🇧🇪" },
  { iso: "bz", name: "Belice", flag: "🇧🇿" },
  { iso: "bj", name: "Benín", flag: "🇧🇯" },
  { iso: "bm", name: "Bermudas", flag: "🇧🇲" },
  { iso: "by", name: "Bielorrusia", flag: "🇧🇾" },
  { iso: "bo", name: "Bolivia", flag: "🇧🇴" },
  { iso: "ba", name: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { iso: "bw", name: "Botsuana", flag: "🇧🇼" },
  { iso: "br", name: "Brasil", flag: "🇧🇷" },
  { iso: "bn", name: "Brunéi", flag: "🇧🇳" },
  { iso: "bg", name: "Bulgaria", flag: "🇧🇬" },
  { iso: "bf", name: "Burkina Faso", flag: "🇧🇫" },
  { iso: "bi", name: "Burundi", flag: "🇧🇮" },
  { iso: "bt", name: "Bután", flag: "🇧🇹" },
  { iso: "cv", name: "Cabo Verde", flag: "🇨🇻" },
  { iso: "kh", name: "Camboya", flag: "🇰🇭" },
  { iso: "cm", name: "Camerún", flag: "🇨🇲" },
  { iso: "ca", name: "Canadá", flag: "🇨🇦" },
  { iso: "qa", name: "Catar", flag: "🇶🇦" },
  { iso: "td", name: "Chad", flag: "🇹🇩" },
  { iso: "cl", name: "Chile", flag: "🇨🇱" },
  { iso: "cn", name: "China", flag: "🇨🇳" },
  { iso: "cy", name: "Chipre", flag: "🇨🇾" },
  { iso: "va", name: "Ciudad del Vaticano", flag: "🇻🇦" },
  { iso: "co", name: "Colombia", flag: "🇨🇴" },
  { iso: "km", name: "Comoras", flag: "🇰🇲" },
  { iso: "kp", name: "Corea del Norte", flag: "🇰🇵" },
  { iso: "kr", name: "Corea del Sur", flag: "🇰🇷" },
  { iso: "ci", name: "Costa de Marfil", flag: "🇨🇮" },
  { iso: "cr", name: "Costa Rica", flag: "🇨🇷" },
  { iso: "hr", name: "Croacia", flag: "🇭🇷" },
  { iso: "cu", name: "Cuba", flag: "🇨🇺" },
  { iso: "dk", name: "Dinamarca", flag: "🇩🇰" },
  { iso: "dm", name: "Dominica", flag: "🇩🇲" },
  { iso: "ec", name: "Ecuador", flag: "🇪🇨" },
  { iso: "eg", name: "Egipto", flag: "🇪🇬" },
  { iso: "sv", name: "El Salvador", flag: "🇸🇻" },
  { iso: "ae", name: "Emiratos Árabes Unidos", flag: "🇦🇪" },
  { iso: "er", name: "Eritrea", flag: "🇪🇷" },
  { iso: "sk", name: "Eslovaquia", flag: "🇸🇰" },
  { iso: "si", name: "Eslovenia", flag: "🇸🇮" },
  { iso: "es", name: "España", flag: "🇪🇸" },
  { iso: "us", name: "Estados Unidos", flag: "🇺🇸" },
  { iso: "ee", name: "Estonia", flag: "🇪🇪" },
  { iso: "et", name: "Etiopía", flag: "🇪🇹" },
  { iso: "ph", name: "Filipinas", flag: "🇵🇭" },
  { iso: "fi", name: "Finlandia", flag: "🇫🇮" },
  { iso: "fj", name: "Fiyi", flag: "🇫🇯" },
  { iso: "fr", name: "Francia", flag: "🇫🇷" },
  { iso: "ga", name: "Gabón", flag: "🇬🇦" },
  { iso: "gm", name: "Gambia", flag: "🇬🇲" },
  { iso: "ge", name: "Georgia", flag: "🇬🇪" },
  { iso: "gh", name: "Ghana", flag: "🇬🇭" },
  { iso: "gi", name: "Gibraltar", flag: "🇬🇮" },
  { iso: "gd", name: "Granada", flag: "🇬🇩" },
  { iso: "gr", name: "Grecia", flag: "🇬🇷" },
  { iso: "gl", name: "Groenlandia", flag: "🇬🇱" },
  { iso: "gt", name: "Guatemala", flag: "🇬🇹" },
  { iso: "gf", name: "Guayana Francesa", flag: "🇬🇫" },
  { iso: "gn", name: "Guinea", flag: "🇬🇳" },
  { iso: "gq", name: "Guinea Ecuatorial", flag: "🇬🇶" },
  { iso: "gw", name: "Guinea-Bisáu", flag: "🇬🇼" },
  { iso: "gy", name: "Guyana", flag: "🇬🇾" },
  { iso: "ht", name: "Haití", flag: "🇭🇹" },
  { iso: "hn", name: "Honduras", flag: "🇭🇳" },
  { iso: "hk", name: "Hong Kong", flag: "🇭🇰" },
  { iso: "hu", name: "Hungría", flag: "🇭🇺" },
  { iso: "in", name: "India", flag: "🇮🇳" },
  { iso: "id", name: "Indonesia", flag: "🇮🇩" },
  { iso: "iq", name: "Irak", flag: "🇮🇶" },
  { iso: "ir", name: "Irán", flag: "🇮🇷" },
  { iso: "ie", name: "Irlanda", flag: "🇮🇪" },
  { iso: "is", name: "Islandia", flag: "🇮🇸" },
  { iso: "ky", name: "Islas Caimán", flag: "🇰🇾" },
  { iso: "fo", name: "Islas Feroe", flag: "🇫🇴" },
  { iso: "fk", name: "Islas Malvinas", flag: "🇫🇰" },
  { iso: "mp", name: "Islas Marianas del Norte", flag: "🇲🇵" },
  { iso: "mh", name: "Islas Marshall", flag: "🇲🇭" },
  { iso: "sb", name: "Islas Salomón", flag: "🇸🇧" },
  { iso: "vg", name: "Islas Vírgenes Británicas", flag: "🇻🇬" },
  { iso: "vi", name: "Islas Vírgenes de EE. UU.", flag: "🇻🇮" },
  { iso: "il", name: "Israel", flag: "🇮🇱" },
  { iso: "it", name: "Italia", flag: "🇮🇹" },
  { iso: "jm", name: "Jamaica", flag: "🇯🇲" },
  { iso: "jp", name: "Japón", flag: "🇯🇵" },
  { iso: "jo", name: "Jordania", flag: "🇯🇴" },
  { iso: "kz", name: "Kazajistán", flag: "🇰🇿" },
  { iso: "ke", name: "Kenia", flag: "🇰🇪" },
  { iso: "kg", name: "Kirguistán", flag: "🇰🇬" },
  { iso: "ki", name: "Kiribati", flag: "🇰🇮" },
  { iso: "kw", name: "Kuwait", flag: "🇰🇼" },
  { iso: "la", name: "Laos", flag: "🇱🇦" },
  { iso: "ls", name: "Lesoto", flag: "🇱🇸" },
  { iso: "lv", name: "Letonia", flag: "🇱🇻" },
  { iso: "lb", name: "Líbano", flag: "🇱🇧" },
  { iso: "lr", name: "Liberia", flag: "🇱🇷" },
  { iso: "ly", name: "Libia", flag: "🇱🇾" },
  { iso: "li", name: "Liechtenstein", flag: "🇱🇮" },
  { iso: "lt", name: "Lituania", flag: "🇱🇹" },
  { iso: "lu", name: "Luxemburgo", flag: "🇱🇺" },
  { iso: "mo", name: "Macao", flag: "🇲🇴" },
  { iso: "mk", name: "Macedonia del Norte", flag: "🇲🇰" },
  { iso: "mg", name: "Madagascar", flag: "🇲🇬" },
  { iso: "my", name: "Malasia", flag: "🇲🇾" },
  { iso: "mw", name: "Malaui", flag: "🇲🇼" },
  { iso: "mv", name: "Maldivas", flag: "🇲🇻" },
  { iso: "ml", name: "Malí", flag: "🇲🇱" },
  { iso: "mt", name: "Malta", flag: "🇲🇹" },
  { iso: "ma", name: "Marruecos", flag: "🇲🇦" },
  { iso: "mq", name: "Martinica", flag: "🇲🇶" },
  { iso: "mu", name: "Mauricio", flag: "🇲🇺" },
  { iso: "mr", name: "Mauritania", flag: "🇲🇷" },
  { iso: "yt", name: "Mayotte", flag: "🇾🇹" },
  { iso: "mx", name: "México", flag: "🇲🇽" },
  { iso: "fm", name: "Micronesia", flag: "🇫🇲" },
  { iso: "md", name: "Moldavia", flag: "🇲🇩" },
  { iso: "mc", name: "Mónaco", flag: "🇲🇨" },
  { iso: "mn", name: "Mongolia", flag: "🇲🇳" },
  { iso: "me", name: "Montenegro", flag: "🇲🇪" },
  { iso: "ms", name: "Montserrat", flag: "🇲🇸" },
  { iso: "mz", name: "Mozambique", flag: "🇲🇿" },
  { iso: "mm", name: "Myanmar", flag: "🇲🇲" },
  { iso: "na", name: "Namibia", flag: "🇳🇦" },
  { iso: "nr", name: "Nauru", flag: "🇳🇷" },
  { iso: "np", name: "Nepal", flag: "🇳🇵" },
  { iso: "ni", name: "Nicaragua", flag: "🇳🇮" },
  { iso: "ne", name: "Níger", flag: "🇳🇪" },
  { iso: "ng", name: "Nigeria", flag: "🇳🇬" },
  { iso: "nu", name: "Niue", flag: "🇳🇺" },
  { iso: "no", name: "Noruega", flag: "🇳🇴" },
  { iso: "nc", name: "Nueva Caledonia", flag: "🇳🇨" },
  { iso: "nz", name: "Nueva Zelanda", flag: "🇳🇿" },
  { iso: "om", name: "Omán", flag: "🇴🇲" },
  { iso: "nl", name: "Países Bajos", flag: "🇳🇱" },
  { iso: "pk", name: "Pakistán", flag: "🇵🇰" },
  { iso: "pw", name: "Palaos", flag: "🇵🇼" },
  { iso: "pa", name: "Panamá", flag: "🇵🇦" },
  { iso: "pg", name: "Papúa Nueva Guinea", flag: "🇵🇬" },
  { iso: "py", name: "Paraguay", flag: "🇵🇾" },
  { iso: "pe", name: "Perú", flag: "🇵🇪" },
  { iso: "pf", name: "Polinesia Francesa", flag: "🇵🇫" },
  { iso: "pl", name: "Polonia", flag: "🇵🇱" },
  { iso: "pt", name: "Portugal", flag: "🇵🇹" },
  { iso: "pr", name: "Puerto Rico", flag: "🇵🇷" },
  { iso: "gb", name: "Reino Unido", flag: "🇬🇧" },
  { iso: "cf", name: "República Centroafricana", flag: "🇨🇫" },
  { iso: "cz", name: "República Checa", flag: "🇨🇿" },
  { iso: "cd", name: "República Democrática del Congo", flag: "🇨🇩" },
  { iso: "do", name: "República Dominicana", flag: "🇩🇴" },
  { iso: "re", name: "Reunión", flag: "🇷🇪" },
  { iso: "rw", name: "Ruanda", flag: "🇷🇼" },
  { iso: "ro", name: "Rumania", flag: "🇷🇴" },
  { iso: "ru", name: "Rusia", flag: "🇷🇺" },
  { iso: "eh", name: "Sahara Occidental", flag: "🇪🇭" },
  { iso: "ws", name: "Samoa", flag: "🇼🇸" },
  { iso: "as", name: "Samoa Americana", flag: "🇦🇸" },
  { iso: "kn", name: "San Cristóbal y Nieves", flag: "🇰🇳" },
  { iso: "sm", name: "San Marino", flag: "🇸🇲" },
  { iso: "pm", name: "San Pedro y Miquelón", flag: "🇵🇲" },
  { iso: "vc", name: "San Vicente y las Granadinas", flag: "🇻🇨" },
  { iso: "sh", name: "Santa Elena, Ascensión y Tristán de Acuña", flag: "🇸🇭" },
  { iso: "lc", name: "Santa Lucía", flag: "🇱🇨" },
  { iso: "st", name: "Santo Tomé y Príncipe", flag: "🇸🇹" },
  { iso: "sn", name: "Senegal", flag: "🇸🇳" },
  { iso: "rs", name: "Serbia", flag: "🇷🇸" },
  { iso: "sc", name: "Seychelles", flag: "🇸🇨" },
  { iso: "sl", name: "Sierra Leona", flag: "🇸🇱" },
  { iso: "sg", name: "Singapur", flag: "🇸🇬" },
  { iso: "sy", name: "Siria", flag: "🇸🇾" },
  { iso: "so", name: "Somalia", flag: "🇸🇴" },
  { iso: "lk", name: "Sri Lanka", flag: "🇱🇰" },
  { iso: "sz", name: "Suazilandia", flag: "🇸🇿" },
  { iso: "za", name: "Sudáfrica", flag: "🇿🇦" },
  { iso: "sd", name: "Sudán", flag: "🇸🇩" },
  { iso: "ss", name: "Sudán del Sur", flag: "🇸🇸" },
  { iso: "se", name: "Suecia", flag: "🇸🇪" },
  { iso: "ch", name: "Suiza", flag: "🇨🇭" },
  { iso: "sr", name: "Surinam", flag: "🇸🇷" },
  { iso: "sj", name: "Svalbard y Jan Mayen", flag: "🇸🇯" },
  { iso: "th", name: "Tailandia", flag: "🇹🇭" },
  { iso: "tw", name: "Taiwán", flag: "🇹🇼" },
  { iso: "tz", name: "Tanzania", flag: "🇹🇿" },
  { iso: "tj", name: "Tayikistán", flag: "🇹🇯" },
  { iso: "io", name: "Territorio Británico del Océano Índico", flag: "🇮🇴" },
  { iso: "tf", name: "Territorios Australes Franceses", flag: "🇹🇫" },
  { iso: "ps", name: "Territorios Palestinos", flag: "🇵🇸" },
  { iso: "tl", name: "Timor Oriental", flag: "🇹🇱" },
  { iso: "tg", name: "Togo", flag: "🇹🇬" },
  { iso: "tk", name: "Tokelau", flag: "🇹🇰" },
  { iso: "to", name: "Tonga", flag: "🇹🇴" },
  { iso: "tt", name: "Trinidad y Tobago", flag: "🇹🇹" },
  { iso: "tn", name: "Túnez", flag: "🇹🇳" },
  { iso: "tc", name: "Turcas y Caicos", flag: "🇹🇨" },
  { iso: "tm", name: "Turkmenistán", flag: "🇹🇲" },
  { iso: "tr", name: "Turquía", flag: "🇹🇷" },
  { iso: "tv", name: "Tuvalu", flag: "🇹🇻" },
  { iso: "ua", name: "Ucrania", flag: "🇺🇦" },
  { iso: "ug", name: "Uganda", flag: "🇺🇬" },
  { iso: "uy", name: "Uruguay", flag: "🇺🇾" },
  { iso: "uz", name: "Uzbekistán", flag: "🇺🇿" },
  { iso: "vu", name: "Vanuatu", flag: "🇻🇺" },
  { iso: "ve", name: "Venezuela", flag: "🇻🇪" },
  { iso: "vn", name: "Vietnam", flag: "🇻🇳" },
  { iso: "wf", name: "Wallis y Futuna", flag: "🇼🇫" },
  { iso: "ye", name: "Yemen", flag: "🇾🇪" },
  { iso: "dj", name: "Yibuti", flag: "🇩🇯" },
  { iso: "zm", name: "Zambia", flag: "🇿🇲" },
  { iso: "zw", name: "Zimbabue", flag: "🇿🇼" }
];
